// Copyright (C) 2026 Julian Corbet
// SPDX-License-Identifier: AGPL-3.0-only

// dotkeeper — P2P repo sync with git history.
package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"

	"github.com/julian-corbet/dotkeeper/internal/activity"
	"github.com/julian-corbet/dotkeeper/internal/benchmarker"
	"github.com/julian-corbet/dotkeeper/internal/config"
	"github.com/julian-corbet/dotkeeper/internal/conflict"
	"github.com/julian-corbet/dotkeeper/internal/discovery"
	"github.com/julian-corbet/dotkeeper/internal/doctor"
	"github.com/julian-corbet/dotkeeper/internal/procnice"
	"github.com/julian-corbet/dotkeeper/internal/reconcile"
	"github.com/julian-corbet/dotkeeper/internal/service"
	"github.com/julian-corbet/dotkeeper/internal/stclient"
	"github.com/julian-corbet/dotkeeper/internal/stengine"
	"github.com/julian-corbet/dotkeeper/internal/transport"
	"github.com/julian-corbet/dotkeeper/internal/watchhealth"
)

// Compile-time conformance: stclient.Client must satisfy the
// transport.SyncthingClient interface. If a future stclient change
// renames or removes a method this transport relies on, the build
// fails here before runtime ever touches the call site.
var _ transport.SyncthingClient = (*stclient.Client)(nil)

// Version is dotkeeper's release version. It overrides Syncthing's embedded
// build.Version for BEP handshake purposes (see internal/stengine).
// Injected via -ldflags="-X main.version=..." at release build time.
var (
	version = "0.6.0-dev"
	commit  = "none"
)

func main() {
	// Wire SIGINT/SIGTERM into the root context so cmd.Context() inside
	// every subcommand carries cancellation. Without ExecuteContext, a
	// long-running reconcile (or any blocking subcommand work) would not
	// observe Ctrl-C until it returned naturally.
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	root := &cobra.Command{
		Use:   "dotkeeper",
		Short: "P2P repo sync with git history",
		Long:  "Embeds Syncthing for real-time file sync between machines.\nUses git for history and backup.",
	}

	root.AddCommand(versionCmd())
	root.AddCommand(initCmd())
	root.AddCommand(statusCmd())
	root.AddCommand(healthCmd())
	root.AddCommand(startCmd())
	root.AddCommand(conflictCmd())
	root.AddCommand(doctorCmd())
	// Declarative commands
	root.AddCommand(reconcileCmd())
	root.AddCommand(identityCmd())
	root.AddCommand(peerCmd())
	root.AddCommand(trackCmd())
	root.AddCommand(untrackCmd())
	root.AddCommand(transportCmd())
	root.AddCommand(benchNowCmd())
	root.AddCommand(subscribeCmd())
	root.AddCommand(unsubscribeCmd())
	root.AddCommand(subscriptionsCmd())
	root.AddCommand(bareInitCmd())

	if err := root.ExecuteContext(ctx); err != nil {
		os.Exit(1)
	}
}

// --- Helpers ---

func engine() *stengine.Engine {
	return stengine.New(config.STConfigDir(), config.STDataDir(), version)
}

func apiClient() *stclient.Client {
	eng := engine()
	key, err := eng.APIKey()
	if err != nil {
		fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: cannot read API key: %v\n", err)
		os.Exit(1)
	}
	return stclient.New(key)
}

func truncateID(id string) string {
	if len(id) >= 8 {
		return id[:8] + "..."
	}
	return id
}

func svcManager() service.Manager {
	mgr, err := service.Detect()
	if err != nil || mgr == nil {
		fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: service detection failed: %v\n", err)
		fmt.Fprintln(os.Stderr, "[dotkeeper] falling back to manual mode — start Syncthing with: dotkeeper start")
		// Return a no-op manager that won't panic
		return &service.NoopManager{}
	}
	return mgr
}

func binaryPath() string {
	exe, err := os.Executable()
	if err != nil {
		return "dotkeeper"
	}
	return exe
}

// --- Commands ---

func versionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print dotkeeper version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("dotkeeper %s (%s)\n", version, commit)
		},
	}
}

func initCmd() *cobra.Command {
	var name string
	var slot int
	var force bool
	var noService bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize this machine for dotkeeper",
		Long:  "Creates machine identity (machine.toml v2), generates Syncthing keys, and installs services.\nRun this on the first machine.",
		Run: func(cmd *cobra.Command, args []string) {
			existing, _ := config.LoadMachineConfigV2()

			if name == "" {
				hostname, _ := os.Hostname()
				name = hostname
			}
			if slot < 0 {
				slot = 0
			}

			// 1. Machine identity (v2 schema). If machine.toml already exists
			// (for example generated by Home Manager), preserve it and only
			// initialise missing runtime state below.
			if existing == nil || force {
				mcfg := &config.MachineConfigV2{
					SchemaVersion:            2,
					Name:                     name,
					Slot:                     uint(slot),
					DefaultCommitPolicy:      "manual",
					DefaultGitInterval:       "daily",
					DefaultSlotOffsetMinutes: 5,
					ReconcileInterval:        "5m",
					DefaultShareWith:         []string{},
					Peers:                    []config.PeerEntry{},
					Discovery: config.DiscoveryConfig{
						ScanRoots:    []string{"~/Documents/GitHub"},
						Exclude:      []string{},
						ScanInterval: "5m",
						ScanDepth:    3,
					},
				}
				if err := config.WriteMachineConfigV2(mcfg); err != nil {
					fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
					os.Exit(1)
				}
				fmt.Printf("[dotkeeper] machine: %s (slot %d)\n", name, slot)
			} else {
				fmt.Printf("[dotkeeper] already initialized as '%s' (slot %d); preserving machine.toml\n", existing.Name, existing.Slot)
			}

			// 2. Syncthing identity
			eng := engine()
			if err := eng.Setup(); err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
				os.Exit(1)
			}
			deviceID, err := eng.DeviceID()
			if err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
				os.Exit(1)
			}
			fmt.Printf("[dotkeeper] Syncthing identity generated\n")
			if err := ensureStateDeviceID(deviceID); err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
				os.Exit(1)
			}
			fmt.Printf("[dotkeeper] state.toml ready\n")

			// 3. Syncthing service
			if noService {
				fmt.Printf("[dotkeeper] service install skipped (--no-service)\n")
			} else {
				mgr := svcManager()
				binPath := binaryPath()
				if err := mgr.InstallSyncthing(binPath); err != nil {
					fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: service install: %v\n", err)
				} else {
					fmt.Printf("[dotkeeper] started Syncthing service (%s)\n", service.PlatformName(mgr))
				}
			}

			// 4. Print result
			fmt.Println()
			fmt.Printf("[dotkeeper] device ID: %s\n", deviceID)
			fmt.Println()
			fmt.Println("[dotkeeper] to add repos, run: dotkeeper track <path>")
			fmt.Println("[dotkeeper] or place a local .dotkeeper.toml in any repo under a scan root")
			fmt.Println("[dotkeeper] then run: dotkeeper reconcile")
		},
	}
	cmd.Flags().StringVar(&name, "name", "", "machine name (default: hostname)")
	cmd.Flags().IntVar(&slot, "slot", -1, "timer slot (default: 0)")
	cmd.Flags().BoolVar(&force, "force", false, "reinitialize")
	cmd.Flags().BoolVar(&noService, "no-service", false, "initialize config/state but do not install or start a service")
	return cmd
}

func ensureStateDeviceID(deviceID string) error {
	return config.MutateStateV2(func(state *config.StateV2) error {
		state.SyncthingDeviceID = deviceID
		return nil
	})
}

// statusCmd shows the machine status: machine name, slot, scan roots,
// peer count from state.toml, tracked override count, and Syncthing connection.
func statusCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Show full status",
		RunE: func(cmd *cobra.Command, args []string) error {
			machine, machineErr := config.LoadMachineConfigV2()
			// A non-nil error means the file exists but failed to parse — tell the
			// user rather than silently treating it as "not initialised".
			if machineErr != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: machine.toml parse failure: %v\n", machineErr)
				return fmt.Errorf("machine.toml parse failure: %w", machineErr)
			}

			state, stateErr := config.LoadStateV2()
			if stateErr != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: state.toml parse failure: %v\n", stateErr)
				return fmt.Errorf("state.toml parse failure: %w", stateErr)
			}

			fmt.Println("=== Machine ===")
			if machine != nil {
				fmt.Printf("  Name: %s\n", machine.Name)
				fmt.Printf("  Slot: %d\n", machine.Slot)
				fmt.Printf("  Scan roots: %s\n", strings.Join(machine.Discovery.ScanRoots, ", "))
			} else {
				fmt.Println("  Not initialized (run 'dotkeeper init')")
			}

			fmt.Printf("\n=== Syncthing (embedded, API %s) ===\n", stclient.APIAddress)
			eng := engine()
			deviceID, _ := eng.DeviceID()

			mgr := svcManager()
			if mgr.IsSyncthingRunning() {
				fmt.Println("  Status: running")
				if deviceID != "" {
					fmt.Printf("  Device ID: %s\n", deviceID)
				}
				fmt.Printf("  Sync port: 12000\n")

				client := apiClient()
				if apiCfg, err := client.GetConfig(); err == nil {
					devices, _ := apiCfg["devices"].([]any)
					folders, _ := apiCfg["folders"].([]any)
					peerCount := 0
					for _, d := range devices {
						dm, _ := d.(map[string]any)
						did, _ := dm["deviceID"].(string)
						if did != deviceID {
							peerCount++
							dname, _ := dm["name"].(string)
							fmt.Printf("  Peer: %s (%s)\n", dname, truncateID(did))
						}
					}
					if peerCount == 0 {
						fmt.Println("  Peers: none")
					}
					fmt.Printf("  Folders: %d\n", len(folders))
				}
			} else {
				fmt.Println("  Status: not running")
				if deviceID != "" {
					fmt.Printf("  Device ID: %s\n", deviceID)
				}
			}

			if state != nil {
				peers := mergedPeersForDisplay()
				if len(peers) > 0 {
					fmt.Printf("\n=== Peers (%d) ===\n", len(peers))
					for _, p := range peers {
						fmt.Printf("  %s: %s (%s)\n", p.Name, truncateID(p.DeviceID), p.Source)
					}
				} else {
					fmt.Println("\n=== Peers ===")
					fmt.Println("  none (pair machines with: dotkeeper reconcile)")
				}

				if len(state.TrackedOverrides) > 0 {
					fmt.Printf("\n=== Tracked overrides (%d) ===\n", len(state.TrackedOverrides))
					for _, p := range state.TrackedOverrides {
						fmt.Printf("  %s\n", config.ContractPath(p))
					}
				}

				if len(state.ObservedRepos) > 0 {
					fmt.Printf("\n=== Observed repos (%d) ===\n", len(state.ObservedRepos))
					for path, obs := range state.ObservedRepos {
						lastReconcile := "never"
						if !obs.LastBackupAt.IsZero() {
							lastReconcile = obs.LastBackupAt.Format("2006-01-02 15:04:05")
						}
						fmt.Printf("  %s (last backup: %s)\n", config.ContractPath(path), lastReconcile)
					}
				}
			}
			return nil
		},
	}
}

func startCmd() *cobra.Command {
	var debug bool

	cmd := &cobra.Command{
		Use:   "start",
		Short: "Start embedded Syncthing + reconcile daemon (foreground, for systemd)",
		Long: "Starts the embedded Syncthing engine, the conflict watcher, and the\n" +
			"reconcile daemon. The reconciler runs on a periodic timer and reacts to\n" +
			"filesystem changes in scan roots, state.toml, and machine.toml.\n\n" +
			"Use --debug to raise the log level to DEBUG.",
		Run: func(cmd *cobra.Command, args []string) {
			// SIGINT/SIGTERM is wired into the root context in main(), so
			// cmd.Context() already cancels on signal. No need to redo it.
			ctx := cmd.Context()

			// Self-apply nice=19 / ioprio=idle before any heavy work
			// starts. The packaged systemd user unit already sets these
			// (Nice=19, IOSchedulingClass=idle, CPUWeight=10) — on those
			// installs LowerSelf is an idempotent no-op. The point is
			// installs that bypass the unit: Docker containers built by
			// third parties, manual `dotkeeper start` in a dev loop,
			// distro packagers who shipped a stripped-down unit. The
			// embedded Syncthing scanner is heavy enough that running
			// without de-prioritisation is user-visible on weaker
			// hardware. Non-Linux platforms compile to a no-op.
			procnice.LowerSelf()

			// Configure slog handler. Writes to os.Stdout because
			// engine.Start later dup2's fd 1 to ~/.local/state/dotkeeper/
			// syncthing.log, and we want our slog output to land in the
			// same file as Syncthing's. Using os.Stderr would route to
			// fd 2 (the systemd journal socket), bypassing the file.
			// This matters more on v0.8+ because Syncthing v2 also uses
			// log/slog (via the default handler), so anything we install
			// here intercepts Syncthing's output too.
			logLevel := slog.LevelInfo
			if debug {
				logLevel = slog.LevelDebug
			}
			logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
				Level: logLevel,
			}))
			slog.SetDefault(logger)

			// Spin up the conflict watcher alongside Syncthing so we
			// log sync-conflict files as soon as they appear. This is a
			// best-effort: if no config is present (first boot) or no
			// managed folders exist yet, we just skip it.
			stopWatcher := startConflictWatcher(ctx)
			defer stopWatcher()

			// Spin up the activity tracker for auto-pause. Independent
			// of the conflict watcher because its purpose is different
			// (per-folder timestamps vs sync-conflict-file detection)
			// and we want activity tracking to keep running even if
			// the conflict watcher fails. Best-effort: if no managed
			// folders exist yet, returns nil tracker and auto-pause is
			// effectively disabled until next reconcile rediscovers.
			tracker := startActivityTracker(ctx, logger)
			defer func() {
				if tracker != nil {
					_ = tracker.Close()
				}
			}()

			// Build the transport manager: pre-classifies every
			// transport's availability, runs initial discovery
			// against every paired peer, builds the per-(transport,
			// peer) cost model graph. Subsequent reconcile cycles
			// consult the manager via Manager.Route to pick the
			// optimal transport per change. The variable currently
			// holds the manager for future use by reconcile and the
			// CLI; this v1.0.0 increment lays the wiring without
			// yet swapping reconcile's stclient-direct propagation
			// for manager-driven routing — that swap lands the
			// observation-feedback loop and the operator-visible
			// behaviour change in one cohesive PR.
			transportMgr := startTransports(ctx, logger)
			propagator := buildPropagator(transportMgr, logger)

			// Spin up the smart-rescan support: watchhealth tracker
			// (per-folder filesystem classification + overflow flags),
			// sleep/wake detector (heartbeat-based, no D-Bus/Cocoa
			// dependency), and the rescan-timestamp recorder used by
			// the backstop check. All three are cheap to leave running;
			// if reconcile decides nothing's drifted, no rescans fire.
			health := startWatchHealth(ctx, logger)
			healthAd := newHealthAdapter(health)
			wakeFlag := startWakeDetector(ctx, logger)
			rescanLog := newRescanLog()
			// Seed the rescan log so the first reconcile after
			// daemon start does not fire a backstop RescanFolderNow
			// for every folder. See seed() comment for rationale.
			rescanLog.seed(managedFolderPathsV5(), time.Now())

			// Forward activity events into the watchhealth tracker so
			// LastReliableEventAt advances. Tracker already drives the
			// auto-pause loop; this just teaches it to also feed
			// watchhealth's liveness clock.
			if tracker != nil && health != nil {
				go forwardActivityToHealth(ctx, tracker, health)
			}

			// Active transport benchmarker: periodically measures
			// synchronous transports per (peer, folder) tuple so the
			// cost model self-tunes even for folders that rarely see
			// organic edits. Skips itself when the local model has
			// converged or when recent organic traffic already
			// provides a fresh observation. Skips Syncthing (async,
			// no inline timing possible) — that transport's params
			// stay at the prior. No-op when no transport manager is
			// available (the build below also no-ops on the same
			// condition).
			startBenchmarker(ctx, transportMgr, logger)

			// Start the reconcile daemon alongside Syncthing.
			startReconcileDaemon(ctx, logger, tracker, healthAd, wakeFlag, rescanLog, propagator)

			eng := engine()
			if err := eng.Start(ctx); err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
				os.Exit(1)
			}
		},
	}
	cmd.Flags().BoolVar(&debug, "debug", false, "enable debug-level logging")
	return cmd
}

// startConflictWatcher starts a conflict.Watcher over every managed
// folder discovered from current state. Returns a cleanup function that
// closes the watcher. Failures are logged, never fatal — Syncthing must
// keep running even if the watcher can't start.
func startConflictWatcher(ctx context.Context) func() {
	roots := managedFolderPathsV5()
	if len(roots) == 0 {
		return func() {}
	}

	w, err := conflict.New(roots)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: conflict watcher: %v\n", err)
		return func() {}
	}

	// Load auto-resolve setting: default true, controlled by machine config
	// in a future version. For now always enabled.
	autoResolve := true

	done := make(chan struct{})
	go func() {
		defer close(done)
		for {
			select {
			case <-ctx.Done():
				return
			case c, ok := <-w.Events():
				if !ok {
					return
				}
				handleConflictEvent(ctx, c, roots, autoResolve)
			case err, ok := <-w.Errors():
				if !ok {
					return
				}
				fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: conflict watcher: %v\n", err)
			}
		}
	}()

	return func() {
		_ = w.Close()
		<-done
	}
}

// handleConflictEvent runs the resolver chain on one detected conflict
// and emits exactly one log line summarising the outcome. Errors from
// individual resolvers become "kept (<reason>)" log lines — they never
// escape to abort the watcher loop.
func handleConflictEvent(ctx context.Context, c conflict.Conflict, roots []string, autoResolve bool) {
	when := c.Timestamp.Format("2006-01-02 15:04:05")

	// Phase 1 behaviour (detection-only) when the user opted out.
	if !autoResolve {
		fmt.Printf("[dotkeeper] kept: %s (from device %s at %s; auto-resolve disabled)\n",
			c.Path, c.DeviceIDShort, when)
		return
	}

	// Try dedup first — cheapest, safest, and covers the commonest
	// "same save on two machines" case without touching git at all.
	if action, err := conflict.ResolveIdentical(c); err == nil && action == conflict.ActionDeduped {
		fmt.Printf("[dotkeeper] deduped: %s (from device %s at %s)\n",
			c.Path, c.DeviceIDShort, when)
		return
	} else if err != nil {
		fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: dedup check %s: %v\n", c.Path, err)
		// Fall through — maybe the merge path still works.
	}

	// Then the 3-way merge. repoRoot is the managed-folder root the
	// conflict lives under, which must also be a git repo for the
	// merge to land; non-repo folders fail gracefully below.
	repoRoot := containingFolder(c.Path, roots)
	action, err := conflict.ResolveTextMerge(ctx, c, repoRoot)
	switch {
	case err != nil:
		fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: merge %s: %v\n", c.Path, err)
		fmt.Printf("[dotkeeper] kept: %s (from device %s at %s; merge error)\n",
			c.Path, c.DeviceIDShort, when)
	case action == conflict.ActionMerged:
		fmt.Printf("[dotkeeper] merged: %s (from device %s at %s)\n",
			c.Path, c.DeviceIDShort, when)
	default:
		fmt.Printf("[dotkeeper] kept: %s (from device %s at %s; manual resolution required)\n",
			c.Path, c.DeviceIDShort, when)
	}
}

// managedFolderPathsV5 returns absolute, existing paths for every managed
// folder discovered from current state: config dir + TrackedOverrides + repos
// found by walking scan roots for .dotkeeper.toml files.
//
// ObservedRepos is intentionally NOT consulted: if a scan_root is removed
// from machine.toml, repos under it should become invisible to the watcher,
// and the next reconcile will prune them from ObservedRepos.
//
// Missing paths are skipped silently. The actual discovery logic lives in
// internal/discovery so both this function and the doctor package share one
// canonical implementation.
func managedFolderPathsV5() []string {
	return discovery.ManagedFolderPaths()
}

func conflictCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "conflict",
		Short: "Inspect and resolve Syncthing sync-conflict files",
	}
	cmd.AddCommand(conflictListCmd())
	cmd.AddCommand(conflictResolveAllCmd())
	cmd.AddCommand(conflictKeepCmd())
	cmd.AddCommand(conflictAcceptCmd())
	return cmd
}

func conflictListCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List sync-conflict files across all managed folders",
		Run: func(cmd *cobra.Command, args []string) {
			roots := managedFolderPathsV5()
			shortToHost := deviceShortToHostnameV5()

			var all []conflict.Conflict
			for _, root := range roots {
				found, err := conflict.Scan(root)
				if err != nil {
					fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: scanning %s: %v\n", root, err)
					continue
				}
				all = append(all, found...)
			}

			if len(all) == 0 {
				fmt.Printf("No sync conflicts detected across %d managed folders.\n", len(roots))
				return
			}

			tw := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
			_, _ = fmt.Fprintln(tw, "FOLDER\tORIGINAL FILE\tTIMESTAMP\tFROM")
			for _, c := range all {
				folder := containingFolder(c.Path, roots)
				rel, err := filepath.Rel(folder, filepath.Dir(c.Path))
				if err != nil || rel == "." {
					rel = ""
				}
				original := c.OriginalName
				if rel != "" {
					original = filepath.Join(rel, c.OriginalName)
				}
				from := c.DeviceIDShort
				if host, ok := shortToHost[c.DeviceIDShort]; ok {
					from = host
				}
				_, _ = fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n",
					config.ContractPath(folder),
					original,
					c.Timestamp.Format("2006-01-02 15:04:05"),
					from,
				)
			}
			_ = tw.Flush()
		},
	}
}

// deviceShortToHostnameV5 builds a lookup from the 7-character short-form
// device ID to the friendly machine name registered in state.toml's Peers.
func deviceShortToHostnameV5() map[string]string {
	out := make(map[string]string)
	state, err := config.LoadStateV2()
	if err != nil || state == nil {
		return out
	}
	for _, p := range state.Peers {
		if len(p.DeviceID) >= 7 {
			out[p.DeviceID[:7]] = p.Name
		}
	}
	return out
}

// conflictResolveAllCmd walks every managed folder, finds conflicts,
// and tries both resolvers in order. Useful as a one-off after an
// extended outage when many conflicts accumulate before the watcher
// goroutine sees them live.
func conflictResolveAllCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "resolve-all",
		Short: "Scan all managed folders and auto-resolve what can be resolved",
		Long: "Walks every managed folder, runs the hash-identical dedup resolver\n" +
			"and the git-merge-file 3-way text resolver on each sync-conflict\n" +
			"file, and prints a per-file summary. Anything left as 'kept' needs\n" +
			"human judgement — diff the pair and merge manually.",
		Run: func(cmd *cobra.Command, args []string) {
			roots := managedFolderPathsV5()

			ctx, cancel := signal.NotifyContext(cmd.Context(), syscall.SIGINT, syscall.SIGTERM)
			defer cancel()

			var all []conflict.Conflict
			for _, root := range roots {
				found, err := conflict.Scan(root)
				if err != nil {
					fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: scanning %s: %v\n", root, err)
					continue
				}
				all = append(all, found...)
			}

			if len(all) == 0 {
				fmt.Printf("No sync conflicts detected across %d managed folders.\n", len(roots))
				return
			}

			var deduped, merged, kept int
			for _, c := range all {
				// Dedup first — cheapest.
				action, err := conflict.ResolveIdentical(c)
				if err != nil {
					fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: dedup %s: %v\n", c.Path, err)
				}
				if action == conflict.ActionDeduped {
					fmt.Printf("deduped: %s\n", c.Path)
					deduped++
					continue
				}

				// Then 3-way merge.
				repoRoot := containingFolder(c.Path, roots)
				action, err = conflict.ResolveTextMerge(ctx, c, repoRoot)
				if err != nil {
					fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: merge %s: %v\n", c.Path, err)
				}
				switch action {
				case conflict.ActionMerged:
					fmt.Printf("merged:  %s\n", c.Path)
					merged++
				default:
					fmt.Printf("kept:    %s\n", c.Path)
					kept++
				}
			}

			fmt.Printf("\nSummary: %d deduped, %d merged, %d kept (manual resolution).\n",
				deduped, merged, kept)
		},
	}
}

// containingFolder returns the watched root that a conflict path lives
// under. Used purely for table display — the conflict.Path is already
// absolute, this just shortens the leading segment.
func containingFolder(path string, roots []string) string {
	best := ""
	for _, r := range roots {
		if strings.HasPrefix(path, r+string(filepath.Separator)) || path == r {
			if len(r) > len(best) {
				best = r
			}
		}
	}
	if best == "" {
		return filepath.Dir(path)
	}
	return best
}

// conflictKeepCmd implements `dotkeeper conflict keep <path>`: drop the
// sync-conflict variant and leave the canonical file untouched. No git
// activity because nothing tracked changed.
func conflictKeepCmd() *cobra.Command {
	var all bool
	cmd := &cobra.Command{
		Use:   "keep <path>",
		Short: "Delete the sync-conflict variant and keep the current file as-is",
		Long: "Removes the .sync-conflict-* file for the given path and leaves the canonical\n" +
			"file unchanged. No git commit — nothing tracked changed.\n\n" +
			"<path> may be either the canonical file or the explicit variant filename.\n" +
			"With --all, processes every pending conflict in every managed folder.",
		Args: func(cmd *cobra.Command, args []string) error {
			if all && len(args) > 0 {
				return fmt.Errorf("--all takes no arguments")
			}
			if !all && len(args) != 1 {
				return fmt.Errorf("exactly one <path> required (or use --all)")
			}
			return nil
		},
		Run: func(cmd *cobra.Command, args []string) {
			if all {
				n := runKeepAll()
				fmt.Printf("kept %d conflict(s)\n", n)
				return
			}
			if err := runKeepOne(args[0]); err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
				os.Exit(1)
			}
		},
	}
	cmd.Flags().BoolVar(&all, "all", false, "apply to every pending conflict across all managed folders")
	return cmd
}

// conflictAcceptCmd implements `dotkeeper conflict accept <path>`:
// replace the canonical file with the variant's contents, delete the
// variant, and commit with a scoped message.
func conflictAcceptCmd() *cobra.Command {
	var all bool
	cmd := &cobra.Command{
		Use:   "accept <path>",
		Short: "Replace the current file with the sync-conflict variant and commit",
		Long: "Overwrites the canonical file with the contents of the .sync-conflict-* variant,\n" +
			"removes the variant, and creates a git commit scoped to that single path:\n" +
			"  auto: accept sync conflict for <relpath> (from <deviceShort>)\n\n" +
			"<path> may be either the canonical file or the explicit variant filename.\n" +
			"With --all, processes every pending conflict in every managed folder;\n" +
			"canonicals with multiple variants are skipped (resolve them explicitly).",
		Args: func(cmd *cobra.Command, args []string) error {
			if all && len(args) > 0 {
				return fmt.Errorf("--all takes no arguments")
			}
			if !all && len(args) != 1 {
				return fmt.Errorf("exactly one <path> required (or use --all)")
			}
			return nil
		},
		Run: func(cmd *cobra.Command, args []string) {
			ctx, cancel := signal.NotifyContext(cmd.Context(), syscall.SIGINT, syscall.SIGTERM)
			defer cancel()

			if all {
				n := runAcceptAll(ctx)
				fmt.Printf("accepted %d conflict(s)\n", n)
				return
			}
			if err := runAcceptOne(ctx, args[0]); err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] ERROR: %v\n", err)
				os.Exit(1)
			}
		},
	}
	cmd.Flags().BoolVar(&all, "all", false, "apply to every pending conflict across all managed folders")
	return cmd
}

// resolveTarget resolves a user-supplied <path> into the exact set of
// variants to act on. Accepts either a canonical path or a variant
// path and always returns absolute paths.
//
// Returns (variants, canonical, nil) on success. Returns a non-nil
// error when:
//   - the path corresponds to no conflict at all ("no conflict for X"),
//   - the path is a canonical with multiple variants (caller must pick
//     one explicitly); the error lists them so the user can copy one.
func resolveTarget(rawPath string) ([]conflict.Conflict, string, error) {
	absPath, err := filepath.Abs(config.ExpandPath(rawPath))
	if err != nil {
		return nil, "", fmt.Errorf("resolving %q: %w", rawPath, err)
	}

	// If the user passed a variant path directly, honour it exactly —
	// we still want to check the same directory for OTHER variants so
	// an "accept this one" on a three-way split doesn't silently leave
	// the other variant behind — but we return only the one they asked
	// for. The --all path handles cross-canonical iteration elsewhere.
	if conflict.IsConflictName(absPath) {
		parsed, err := conflict.Parse(filepath.Base(absPath))
		if err != nil {
			return nil, "", fmt.Errorf("parsing %q: %w", absPath, err)
		}
		if _, err := os.Stat(absPath); err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return nil, "", fmt.Errorf("no conflict for %s", rawPath)
			}
			return nil, "", fmt.Errorf("stat %s: %w", absPath, err)
		}
		parsed.Path = absPath
		canonical := filepath.Join(filepath.Dir(absPath), parsed.OriginalName)
		return []conflict.Conflict{*parsed}, canonical, nil
	}

	// Canonical path: find every variant next to it.
	variants, err := conflict.FindVariants(absPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, "", fmt.Errorf("no conflict for %s", rawPath)
		}
		return nil, "", fmt.Errorf("scanning %s: %w", filepath.Dir(absPath), err)
	}
	if len(variants) == 0 {
		return nil, "", fmt.Errorf("no conflict for %s", rawPath)
	}
	if len(variants) > 1 {
		var b strings.Builder
		fmt.Fprintf(&b, "%s has %d variants — pass one explicitly:", rawPath, len(variants))
		for _, v := range variants {
			fmt.Fprintf(&b, "\n  %s", v.Path)
		}
		return nil, "", fmt.Errorf("%s", b.String())
	}
	return variants, absPath, nil
}

// runKeepOne implements `dotkeeper conflict keep <path>` for a single
// path argument.
func runKeepOne(rawPath string) error {
	variants, _, err := resolveTarget(rawPath)
	if err != nil {
		return err
	}
	for _, v := range variants {
		if err := conflict.Keep(v); err != nil {
			return fmt.Errorf("keep %s: %w", v.Path, err)
		}
		fmt.Printf("kept: %s\n", v.Path)
	}
	return nil
}

// runKeepAll iterates every conflict across every managed folder and
// calls Keep on each. Errors are logged but do not abort the sweep —
// one stubborn variant shouldn't prevent cleanup of the rest.
func runKeepAll() int {
	roots := managedFolderPathsV5()
	var kept int
	for _, root := range roots {
		found, err := conflict.Scan(root)
		if err != nil {
			fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: scanning %s: %v\n", root, err)
			continue
		}
		for _, c := range found {
			if err := conflict.Keep(c); err != nil {
				fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: keep %s: %v\n", c.Path, err)
				continue
			}
			fmt.Printf("kept: %s\n", c.Path)
			kept++
		}
	}
	return kept
}

// runAcceptOne implements `dotkeeper conflict accept <path>` for a
// single path argument.
func runAcceptOne(ctx context.Context, rawPath string) error {
	variants, canonical, err := resolveTarget(rawPath)
	if err != nil {
		return err
	}
	roots := managedFolderPathsV5()
	repoRoot := containingFolder(canonical, roots)
	for _, v := range variants {
		if err := conflict.Accept(ctx, v, repoRoot); err != nil {
			return fmt.Errorf("accept %s: %w", v.Path, err)
		}
		fmt.Printf("accepted: %s\n", v.Path)
	}
	return nil
}

// runAcceptAll iterates every conflict across every managed folder.
// Canonicals with multiple variants are skipped with a warning — the
// user must resolve them explicitly so they pick the one they want.
func runAcceptAll(ctx context.Context) int {
	roots := managedFolderPathsV5()
	var accepted int

	// Group conflicts by canonical path first so we can detect and
	// skip multi-variant cases before any disk writes happen.
	type key struct{ canonical string }
	groups := make(map[key][]conflict.Conflict)
	for _, root := range roots {
		found, err := conflict.Scan(root)
		if err != nil {
			fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: scanning %s: %v\n", root, err)
			continue
		}
		for _, c := range found {
			canonical := filepath.Join(filepath.Dir(c.Path), c.OriginalName)
			k := key{canonical: canonical}
			groups[k] = append(groups[k], c)
		}
	}

	for k, variants := range groups {
		if len(variants) > 1 {
			fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: %s has %d variants — skipping; resolve explicitly\n",
				k.canonical, len(variants))
			continue
		}
		v := variants[0]
		repoRoot := containingFolder(k.canonical, roots)
		if err := conflict.Accept(ctx, v, repoRoot); err != nil {
			fmt.Fprintf(os.Stderr, "[dotkeeper] WARNING: accept %s: %v\n", v.Path, err)
			continue
		}
		fmt.Printf("accepted: %s\n", v.Path)
		accepted++
	}
	return accepted
}

// doctorCmd wires `dotkeeper doctor` to the internal/doctor orchestrator.
// Supports --json for machine-readable output. Exit codes:
//
//	0 — no failures (warnings don't count)
//	1 — at least one failed check
//	2 — catastrophic (can't construct the check set at all)
func doctorCmd() *cobra.Command {
	var asJSON bool
	cmd := &cobra.Command{
		Use:   "doctor",
		Short: "Run self-diagnostic checks and report health",
		Long: "Runs a sequence of small checks (version, config, service, Syncthing API,\n" +
			"peers, folders, git remotes, backup timer, sync conflicts) and prints a\n" +
			"one-line verdict per check. Output is useful to paste into an issue report.\n\n" +
			"Pass --json for machine-readable output.",
		Run: func(cmd *cobra.Command, args []string) {
			ctx, cancel := signal.NotifyContext(cmd.Context(), syscall.SIGINT, syscall.SIGTERM)
			defer cancel()

			checks := buildDoctorChecks()
			var fails int
			if asJSON {
				fails = doctor.RunJSON(ctx, checks, os.Stdout)
			} else {
				fails = doctor.Run(ctx, checks, os.Stdout)
			}
			if fails > 0 {
				os.Exit(1)
			}
		},
	}
	cmd.Flags().BoolVar(&asJSON, "json", false, "emit machine-readable JSON output")
	return cmd
}

// buildDoctorChecks constructs the ordered list of checks the doctor
// subcommand runs. Dependencies (service manager, Syncthing client) are
// resolved best-effort — if any can't be built, the relevant checks
// will still report cleanly (Warn/Fail with a hint) rather than aborting.
func buildDoctorChecks() []doctor.Check {
	mgr, _ := service.Detect()
	// Build an stclient best-effort: the API key is only readable once
	// Syncthing has been initialised. On a fresh box we simply pass a
	// nil client and let SyncthingAPICheck report a clear Fail.
	var client doctor.STClient
	if key, err := engine().APIKey(); err == nil {
		client = stclient.New(key)
	}
	return []doctor.Check{
		doctor.VersionCheck{Version: version, Commit: commit},
		doctor.ConfigCheck{},
		doctor.ServiceCheck{Manager: mgr},
		doctor.SyncthingAPICheck{Client: client},
		doctor.PeersCheck{
			Client:      client,
			LoadMachine: config.LoadMachineConfigV2,
			LoadState:   config.LoadStateV2,
		},
		doctor.FoldersCheck{Client: client},
		doctor.GitRemotesCheck{},
		doctor.LocalMetadataCheck{},
		doctor.ConflictsCheck{},
	}
}

// unused keeps the time import live for the statusCmd's time.Time formatting.
var _ = time.Time{}

// startTransports constructs every transport implementation that
// dotkeeper supports, wires them into a Manager, and triggers
// initial discovery for every known peer. Returns the Manager so
// reconcile and the CLI can consult it.
//
// Transport ordering matters: Manager.Route uses list order as
// tie-breaker when two transports predict equal costs, and
// Syncthing is intentionally listed LAST so other transports win
// any tie. Rationale: Syncthing is the universal fallback that
// always works; "use the alternative when it's at least as good"
// is the desired bias.
//
// Discovery runs once at startup. Subsequent refresh happens only
// on explicit triggers (wake from suspend → reconcile loop calls
// Manager.InvalidatePeer for each peer, forcing rediscovery on
// next access; an explicit `dotkeeper transport rediscover` CLI
// verb is a planned extension). No periodic background probing —
// peer connectivity is topology, not weather.
func startTransports(ctx context.Context, logger *slog.Logger) *transport.Manager {
	transports := buildTransportList()

	names := make([]string, 0, len(transports))
	for _, t := range transports {
		names = append(names, t.Name()+"("+availabilityString(t.Available())+")")
	}
	logger.InfoContext(ctx, "transports configured", "list", strings.Join(names, ","))

	mgr := transport.NewManager(transports)

	// Initial discovery for each configured peer. Pulled from
	// machine.toml directly because the desired-state provider's
	// peer list is the authoritative source and we want it
	// available before reconcile runs its first cycle.
	if machine, err := config.LoadMachineConfigV2(); err == nil && machine != nil {
		for _, p := range machine.Peers {
			peer := transport.Peer{
				Name:     p.Name,
				DeviceID: p.DeviceID,
				Hostname: p.Name, // v1.0 defaults Hostname to Name; v1.1 will let users override
			}
			mgr.Discover(ctx, peer)
			// Log which transports were found reachable. The
			// "best for this size" choice happens per-change via
			// Manager.Route; at startup we just report topology.
			routes, _ := mgr.RoutesFor(peer.Name)
			var reachable []string
			for name, entry := range routes.Entries {
				if entry.Reachable {
					reachable = append(reachable, name)
				}
			}
			logger.InfoContext(ctx, "peer discovery completed",
				"peer", peer.Name,
				"reachable", strings.Join(reachable, ","))
		}
	}
	return mgr
}

// buildTransportList constructs every transport implementation
// dotkeeper supports on this build. Order is load-bearing — see
// startTransports for the tie-break rationale.
//
// Auto-detection happens here: any transport whose prerequisites
// can be checked without blocking is queried; transports that
// require remote calls to determine availability defer to their
// own Available() at runtime.
func buildTransportList() []transport.Transport {
	var transports []transport.Transport

	// GitSSH variants are registered when their resolver's
	// prerequisites are satisfied on this host. v1.0.0 ships one
	// resolver (Tailscale); the Resolver interface is the seam for
	// mDNS and static-hub variants in follow-up releases. The
	// order of resolvers here is the order the Manager consults
	// when ranking transports for a peer; the cost model decides
	// per-change which one is actually used.
	ts := transport.NewTailscaleResolver()
	if ts.Available() {
		transports = append(transports, transport.NewGitSSHTransport(ts))
		// Mutagen runs over the same SSH path as GitSSH; if the
		// resolver is good, Mutagen tries to claim itself too. The
		// transport's own Available() guards against `mutagen`
		// missing on PATH, so this entry is a no-op on hosts
		// without it.
		mtg := transport.NewMutagenTransport(ts)
		if mtg.Available() {
			transports = append(transports, mtg)
		}
	}

	// Syncthing always last. It's the universal fallback — every
	// dotkeeper install has it built in, so it's never absent.
	if key, err := engine().APIKey(); err == nil {
		transports = append(transports, transport.NewSyncthingTransport(stclient.New(key)))
	}

	return transports
}

func availabilityString(b bool) string {
	if b {
		return "available"
	}
	return "unavailable"
}

// forwardActivityToHealth subscribes to the activity tracker's
// Hints channel and forwards each event into the watchhealth
// tracker as MarkEventDelivered. This keeps LastReliableEventAt
// fresh on every watched folder so the "watcher has been silent
// for too long" liveness check (planned for v0.9.8) has accurate
// data. v0.9.7 doesn't yet branch on this field but populating it
// avoids a "missing data" issue when the check is added later.
func forwardActivityToHealth(ctx context.Context, tracker *activity.Tracker, health *watchhealth.Tracker) {
	for {
		select {
		case <-ctx.Done():
			return
		case root, ok := <-tracker.Hints():
			if !ok {
				return
			}
			health.MarkEventDelivered(root, time.Now())
		}
	}
}

// startWatchHealth instantiates the watchhealth.Tracker and
// pre-classifies every currently-managed folder. Returns the
// tracker (typed pointer rather than interface) so callers can
// supply it both as a HealthQuerier to the provider and as a
// HealthResetter to the applier.
//
// Reclassification on the fly (folders added after startup) is
// deferred to v0.9.8 — same trade-off as the activity tracker:
// folders added post-startup don't get smart rescan until next
// service restart, which is recoverable.
func startWatchHealth(ctx context.Context, logger *slog.Logger) *watchhealth.Tracker {
	wh := watchhealth.New()
	for _, root := range managedFolderPathsV5() {
		st := wh.Register(root)
		logger.InfoContext(ctx, "watchhealth classified folder",
			"path", root,
			"fs", st.FilesystemType,
			"kind", st.Kind.String())
	}
	return wh
}

// startWakeDetector spawns the heartbeat-based suspend/resume
// detector and returns a WakeFlag adapter that the provider can
// Take() once per cycle. The detector runs at 30s ticks and emits
// when wall-clock advances by >60s between ticks.
func startWakeDetector(ctx context.Context, logger *slog.Logger) reconcileWakeFlag {
	events := watchhealth.StartSleepDetector(ctx, 30*time.Second)
	wf := &wakeFlag{}
	go func() {
		for ev := range events {
			logger.InfoContext(ctx, "suspend/resume detected", "gap", ev.Gap.String())
			wf.set()
		}
	}()
	return wf
}

// wakeFlag is a one-shot bool consumed by reconcile via Take().
// The detector goroutine sets it; the provider consumes it once
// per cycle.
type wakeFlag struct {
	mu  sync.Mutex
	hot bool
}

func (w *wakeFlag) set() {
	w.mu.Lock()
	w.hot = true
	w.mu.Unlock()
}

func (w *wakeFlag) Take() bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	v := w.hot
	w.hot = false
	return v
}

// reconcileWakeFlag is a local interface alias matching reconcile's
// WakeFlag so the public API stays narrow.
type reconcileWakeFlag interface {
	Take() bool
}

// buildPropagator constructs the v1.0.0 daemon-side
// CommitPropagator. Returns nil when no transport manager exists
// (defensive — reconcile degrades to "no peer propagation," same
// as releases before v1.0.0).
//
// Both the peer roster and the managed-folder set are queried
// FRESH on every PropagateNewCommit call. machine.toml is small
// and managedFolderPathsV5 walks the same in-process state that
// reconcile updates, so the per-commit cost is dominated by the
// existing push work, not the lookups. The freshness matters
// because dotkeeper users edit machine.toml or run `dotkeeper
// track` without restarting the daemon and reasonably expect the
// next commit to find the change.
func buildPropagator(mgr *transport.Manager, logger *slog.Logger) reconcile.CommitPropagator {
	if mgr == nil {
		return nil
	}
	return newDaemonPropagatorWithSources(mgr, livePeersSource(), livePropagatorFoldersSource(), logger)
}

// livePeersSource returns a closure that re-reads machine.toml on
// every invocation. Shared between the propagator and the active
// benchmarker so both surfaces stay in sync with operator config
// edits without a daemon restart.
func livePeersSource() func() []transport.Peer {
	return func() []transport.Peer {
		machine, err := config.LoadMachineConfigV2()
		if err != nil || machine == nil {
			return nil
		}
		peers := make([]transport.Peer, 0, len(machine.Peers))
		for _, p := range machine.Peers {
			peers = append(peers, transport.Peer{
				Name:     p.Name,
				DeviceID: p.DeviceID,
				Hostname: p.Name,
			})
		}
		return peers
	}
}

// livePropagatorFoldersSource returns a closure shaped for the
// propagator (path-keyed map). Re-walks managedFolderPathsV5 on
// each call so freshly-added folders propagate without restart.
func livePropagatorFoldersSource() func() map[string]transport.Folder {
	return func() map[string]transport.Folder {
		roots := managedFolderPathsV5()
		byPath := make(map[string]transport.Folder, len(roots))
		for _, root := range roots {
			byPath[root] = transport.Folder{
				ID:   filepath.Base(root),
				Path: root,
			}
		}
		return byPath
	}
}

// liveBenchmarkerFoldersSource returns a closure shaped for the
// benchmarker (flat slice). Same freshness contract as the
// propagator's source.
func liveBenchmarkerFoldersSource() func() []transport.Folder {
	return func() []transport.Folder {
		roots := managedFolderPathsV5()
		out := make([]transport.Folder, 0, len(roots))
		for _, root := range roots {
			out = append(out, transport.Folder{
				ID:   filepath.Base(root),
				Path: root,
			})
		}
		return out
	}
}

// startBenchmarker spins up the active-transport benchmarker if
// the transport manager is available. No-op otherwise — without a
// manager there's nothing to benchmark and the daemon degrades to
// pre-v1.1.22 behaviour (cost model learns only from organic
// observations).
func startBenchmarker(ctx context.Context, mgr *transport.Manager, logger *slog.Logger) {
	if mgr == nil {
		return
	}
	b := benchmarker.New(mgr, liveBenchmarkerFoldersSource(), livePeersSource(), logger, benchmarker.Options{})
	go b.Run(ctx)
}

// daemonPropagator implements reconcile.CommitPropagator on top of
// the v1.0.0 transport.Manager. For each successful local commit,
// it fans out to every paired peer, asks the Manager for the
// optimal transport given the change's measured size, executes
// the push via Transport.PropagateChange, and feeds the observed
// elapsed time back into the Manager's cost model.
//
// All work is best-effort: a per-peer push failure logs but does
// not propagate to the caller, because the local commit is
// canonical state and peers eventually catch up via Syncthing's
// universal fallback or via subsequent reconcile cycles.
//
// Freshness: the peer roster and folder map are queried via the
// peersSource / foldersSource callbacks on every PropagateNewCommit
// invocation. This means peers added to machine.toml or folders
// added via `dotkeeper track` after daemon startup are picked up on
// the very next commit cycle, rather than only after a daemon
// restart. The previous design captured both at construction and
// silently skipped late-added peers/folders — a real source of
// "I added the peer, why isn't it receiving pushes?" friction.
type daemonPropagator struct {
	mgr    *transport.Manager
	logger *slog.Logger

	// peersSource returns the current peer roster. Called on each
	// PropagateNewCommit; cost is one machine.toml read which is
	// noise on the post-commit hot path.
	peersSource func() []transport.Peer

	// foldersSource returns the current managed-folder map keyed by
	// absolute working-tree path. Same freshness contract as
	// peersSource.
	foldersSource func() map[string]transport.Folder
}

// newDaemonPropagator constructs a propagator with fixed peer and
// folder snapshots — the historical "captured at startup" semantics
// preserved for the tests that pass explicit slices. Production
// callers should use newDaemonPropagatorWithSources so peer/folder
// additions become visible on the next commit, not the next restart.
func newDaemonPropagator(mgr *transport.Manager, peers []transport.Peer, folders []transport.Folder, logger *slog.Logger) *daemonPropagator {
	byPath := make(map[string]transport.Folder, len(folders))
	for _, f := range folders {
		byPath[f.Path] = f
	}
	return newDaemonPropagatorWithSources(mgr,
		func() []transport.Peer { return peers },
		func() map[string]transport.Folder { return byPath },
		logger)
}

// newDaemonPropagatorWithSources is the source-based constructor:
// the propagator calls peersSource and foldersSource fresh on every
// PropagateNewCommit. nil callbacks are treated as "no peers / no
// folders" — propagator becomes a no-op, which is the right
// degenerate behaviour when machine state isn't loadable.
func newDaemonPropagatorWithSources(mgr *transport.Manager, peersSource func() []transport.Peer, foldersSource func() map[string]transport.Folder, logger *slog.Logger) *daemonPropagator {
	return &daemonPropagator{
		mgr:           mgr,
		logger:        logger,
		peersSource:   peersSource,
		foldersSource: foldersSource,
	}
}

func (p *daemonPropagator) PropagateNewCommit(ctx context.Context, folderPath string) {
	if p.mgr == nil {
		return
	}
	var peers []transport.Peer
	if p.peersSource != nil {
		peers = p.peersSource()
	}
	if len(peers) == 0 {
		return
	}
	var folders map[string]transport.Folder
	if p.foldersSource != nil {
		folders = p.foldersSource()
	}
	folder, ok := folders[folderPath]
	if !ok {
		p.logger.DebugContext(ctx, "propagator: no folder known for path", "path", folderPath)
		return
	}

	// Approximate change size from the last commit's diff. Used by
	// Manager.Route to pick between transports; the cost model
	// improves with every observation, so the initial estimate
	// doesn't need to be perfect.
	sizeBytes := estimateLastCommitSize(folderPath)

	change := transport.Change{
		Folder:   folder,
		SizeHint: sizeBytes,
		Kind:     transport.ChangeKindUnknown,
	}

	for _, peer := range peers {
		t, err := p.mgr.Route(change, peer.Name)
		if err != nil {
			p.logger.WarnContext(ctx, "propagator: no route to peer",
				"peer", peer.Name, "err", err)
			continue
		}
		start := time.Now()
		if err := t.PropagateChange(ctx, change, peer); err != nil {
			p.logger.WarnContext(ctx, "propagator: push failed",
				"peer", peer.Name, "transport", t.Name(), "err", err)
			continue
		}
		elapsed := time.Since(start)
		// Only synchronous transports produce a duration that
		// reflects real work. SyncthingTransport.PropagateChange
		// is a no-op (BEP gossip handles the actual propagation in
		// the background), so its ~µs elapsed would teach the cost
		// model that it's infinitely fast — defeating Manager.Route
		// for every subsequent decision.
		if t.PropagatesSynchronously() {
			p.mgr.RecordTransfer(t.Name(), peer.Name, folder.ID, sizeBytes, elapsed)
			p.logger.InfoContext(ctx, "propagator: pushed",
				"peer", peer.Name,
				"transport", t.Name(),
				"bytes", sizeBytes,
				"elapsed", elapsed.Round(time.Millisecond).String())
		} else {
			p.logger.InfoContext(ctx, "propagator: queued for async transport",
				"peer", peer.Name,
				"transport", t.Name(),
				"bytes", sizeBytes)
		}
	}
}

// estimateLastCommitSize approximates the byte count of the
// most-recent commit's changes by parsing `git diff --shortstat
// HEAD~1 HEAD`. Returns 0 (interpreted by Manager.Route as
// "unknown size; fall back to defaults") when the diff query
// fails — e.g. on the very first commit where HEAD~1 doesn't
// exist.
//
// The estimate is an upper bound — shortstat counts inserted +
// deleted line bytes but ignores binary deltas. For dotkeeper's
// text-heavy workload that's a fine approximation; the cost model
// learns the per-byte multiplier empirically anyway.
func estimateLastCommitSize(folderPath string) int64 {
	cmd := exec.Command("git", "diff", "--shortstat", "HEAD~1", "HEAD")
	cmd.Dir = folderPath
	out, err := cmd.Output()
	if err != nil {
		return 0
	}
	// shortstat format: " N files changed, X insertions(+), Y deletions(-)"
	// (singular forms "insertion(+)" / "deletion(-)" for X=1). We
	// extract the integer immediately preceding each "insertion" /
	// "deletion" token by walking backward through whitespace and
	// digits. A regex would be cleaner but pulls in regexp for a
	// one-off use; the walk-backward parser is ~10 lines and has
	// no other dependencies.
	s := string(out)
	inserts := numberBefore(s, "insertion")
	deletes := numberBefore(s, "deletion")
	// 50 bytes/line is a rough proxy for the cost model — the model's
	// per-byte coefficient is learned online, so any consistent
	// scaling factor works equivalently. We pick 50 because it's a
	// reasonable average source-line length and produces sizes in
	// the same order of magnitude as actual transfer payloads.
	return (inserts + deletes) * 50
}

// numberBefore returns the integer immediately preceding `marker`
// in `s`, or 0 when the marker is absent or no integer precedes it.
// Walks backward from the marker, skipping a single whitespace
// character (e.g. between "10" and "insertions"), then accumulates
// consecutive digits.
func numberBefore(s, marker string) int64 {
	idx := strings.Index(s, marker)
	if idx <= 0 {
		return 0
	}
	// Walk backward over whitespace.
	end := idx
	for end > 0 && (s[end-1] == ' ' || s[end-1] == '\t') {
		end--
	}
	// Walk backward over digits.
	start := end
	for start > 0 && s[start-1] >= '0' && s[start-1] <= '9' {
		start--
	}
	if start == end {
		return 0
	}
	var n int64
	for i := start; i < end; i++ {
		n = n*10 + int64(s[i]-'0')
	}
	return n
}

// rescanLog is the in-memory store of last-rescan timestamps per
// folder path. Implements both reconcile.LastRescanRecorder (called
// by the applier on successful rescan) and reconcile.LastRescanQuerier
// (called by the provider when populating Observed). Resets on
// daemon restart — the cost is one extra rescan per folder after
// each restart, which is benign.
type rescanLog struct {
	mu      sync.RWMutex
	entries map[string]time.Time
}

func newRescanLog() *rescanLog {
	return &rescanLog{entries: make(map[string]time.Time)}
}

// seedRescanLog populates the log with time.Now() for every
// currently-managed folder root. Called once at daemon startup so
// the first reconcile sees "just rescanned" rather than "never
// rescanned." Without this seeding, v0.9.7's backstop logic fires
// a RescanFolderNow for every folder within seconds of daemon
// start — on a multi-folder fleet, that burst can overwhelm
// Syncthing's REST endpoint (one folder timed out at the default
// 5s when 22 rescans hit at once during the v0.9.7 deploy).
//
// Side-effect: a fresh daemon defers all backstop rescans by one
// backstop interval (7 days for reliable filesystems, 24h for
// unreliable). For the daemon-restart case that's correct: we
// don't actually need to rescan; nothing meaningful has happened.
// For the first-ever boot case there's a small theoretical window
// where Syncthing's own scan history is empty too, but Syncthing
// always scans at startup independent of dotkeeper, so the bases
// are covered.
func (r *rescanLog) seed(paths []string, at time.Time) {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, p := range paths {
		// Don't overwrite an existing entry — the seed represents
		// a baseline, not a forced reset. (Currently the only call
		// site is daemon startup where the map is freshly empty,
		// but the guard is cheap and future-proofs against e.g.
		// re-seeding on folder-set change.)
		if _, ok := r.entries[p]; !ok {
			r.entries[p] = at
		}
	}
}

func (r *rescanLog) RecordRescan(path string, at time.Time) {
	r.mu.Lock()
	r.entries[path] = at
	r.mu.Unlock()
}

func (r *rescanLog) LastRescan(path string) (time.Time, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	v, ok := r.entries[path]
	return v, ok
}

// startActivityTracker creates an activity.Tracker over every
// currently-managed folder root. Returns nil (auto-pause disabled)
// when there are no managed folders or the tracker can't start —
// both are non-fatal because the daemon must keep running.
//
// Folders added or removed *after* startup are not reflected in the
// tracker's watch set in this v0.9.6 first cut. The trade-off:
// folders added after startup don't auto-pause until the next daemon
// restart; folders removed after startup have their watches dangle
// until the same. Both are recoverable on the next service restart.
// A proper "reload roots on reconcile-detected folder set change" is
// possible but adds enough complexity that it's worth waiting for a
// reported user impact before shipping it.
func startActivityTracker(ctx context.Context, logger *slog.Logger) *activity.Tracker {
	roots := managedFolderPathsV5()
	if len(roots) == 0 {
		logger.InfoContext(ctx, "activity tracker disabled (no managed folders yet)")
		return nil
	}
	tr, err := activity.New(roots)
	if err != nil {
		logger.WarnContext(ctx, "activity tracker failed to start; auto-pause disabled", "err", err)
		return nil
	}
	logger.InfoContext(ctx, "activity tracker started", "roots", len(roots))
	return tr
}

// bareInitCmd configures peer-side git repositories so that
// dotkeeper's GitSSHTransport can push directly to them. The peer
// side runs `git config receive.denyCurrentBranch updateInstead`
// in every tracked folder — that tells git to accept pushes to
// the currently-checked-out branch AND atomically update the
// working tree on each push.
//
// Why this design (vs the more conventional bare-repo +
// post-receive hook): one configuration knob per folder instead
// of provisioning a bare repo + installing hooks, no second
// authoritative copy of the data on the peer, no path-mapping
// problem (peer's working tree lives at the same path as the
// local one — already a dotkeeper invariant via `scan_roots`),
// and natural coexistence with Syncthing (both transports write
// to the same working tree; identical content is a no-op for
// either).
//
// Prerequisites the operator must satisfy:
//   - SSH key access from this host to the peer's account
//     (authorized_keys configured ahead of time)
//   - Same folder path on the peer as on this host (the v1.0.0
//     constraint; a per-peer path map is a planned extension)
//   - Each tracked folder exists as a git working tree on the
//     peer (dotkeeper-managed folders are git working trees by
//     definition)
func bareInitCmd() *cobra.Command {
	var peerName string
	var hostOverride string
	cmd := &cobra.Command{
		Use:   "bare-init [--peer=NAME] [--host=USER@ADDR]",
		Short: "Configure peer-side git repos for direct-push transport",
		Long: "For each folder tracked by dotkeeper on this host, SSH to\n" +
			"the named peer (or every peer in machine.toml if --peer is\n" +
			"omitted) and run:\n\n" +
			"  git -C <folder> config receive.denyCurrentBranch updateInstead\n\n" +
			"This enables `git push` directly to the peer's working tree —\n" +
			"the basis of dotkeeper's v1.0.0 GitSSHTransport. Idempotent:\n" +
			"re-running on an already-configured folder is a no-op.\n\n" +
			"Peer address resolution order:\n" +
			"  1. --host=USER@ADDR (operator override)\n" +
			"  2. Any registered resolver that knows the peer\n" +
			"     (v1.0.0 ships a Tailscale resolver; mDNS and\n" +
			"     static-hub variants are planned)\n" +
			"  3. The peer.Name itself (assume it's resolvable as a\n" +
			"     hostname via the operator's /etc/hosts, DNS, or\n" +
			"     SSH config)\n\n" +
			"Prerequisites: SSH key access already configured to the\n" +
			"peer (`ssh peer-address true` must succeed); each folder\n" +
			"exists at the same absolute path on both hosts (the v1.0.0\n" +
			"path-mirroring constraint).",
		RunE: func(cmd *cobra.Command, args []string) error {
			machine, err := config.LoadMachineConfigV2()
			if err != nil || machine == nil {
				return fmt.Errorf("load machine config: %w", err)
			}

			peers := machine.Peers
			if peerName != "" {
				filtered := peers[:0]
				for _, p := range peers {
					if p.Name == peerName {
						filtered = append(filtered, p)
					}
				}
				if len(filtered) == 0 {
					return fmt.Errorf("peer %q not found in machine config", peerName)
				}
				peers = filtered
			}
			if len(peers) == 0 {
				return fmt.Errorf("no peers configured; pair a peer first with `dotkeeper peer add`")
			}

			folders := managedFolderPathsV5()
			if len(folders) == 0 {
				return fmt.Errorf("no managed folders; track at least one before bare-init")
			}

			// Construct the list of available resolvers in
			// preference order. v1.0.0 ships one resolver
			// (Tailscale); mDNS and static-hub variants are
			// planned extensions. Each resolver's Available() is
			// consulted lazily inside resolveBareInitAddress so an
			// unconfigured resolver (e.g. the resolver's
			// prerequisite tool isn't installed) simply
			// contributes nothing.
			resolvers := []transport.Resolver{
				transport.NewTailscaleResolver(),
			}

			if hostOverride != "" && len(peers) > 1 {
				return fmt.Errorf("--host can only be used together with --peer (a single override address can't apply to every peer)")
			}

			ctx := cmd.Context()
			out := cmd.OutOrStdout()
			anyErr := false
			for _, p := range peers {
				addr, source, err := resolveBareInitAddress(ctx, p, hostOverride, resolvers)
				if err != nil {
					_, _ = fmt.Fprintf(out, "peer %q: skip (%v)\n", p.Name, err)
					anyErr = true
					continue
				}
				for _, folder := range folders {
					_, _ = fmt.Fprintf(out, "peer %q (%s via %s) folder %q: configuring receive.denyCurrentBranch=updateInstead\n",
						p.Name, addr, source, folder)
					output, err := bareInitSSHRunner(ctx, addr,
						"git", "-C", shellQuote(folder),
						"config", "receive.denyCurrentBranch", "updateInstead")
					if err != nil {
						_, _ = fmt.Fprintf(out, "  FAILED: %v: %s\n", err, strings.TrimSpace(string(output)))
						anyErr = true
						continue
					}
					_, _ = fmt.Fprintf(out, "  ok\n")
				}
			}
			if anyErr {
				return fmt.Errorf("bare-init completed with errors; see output above")
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&peerName, "peer", "", "configure only this peer (default: every peer)")
	cmd.Flags().StringVar(&hostOverride, "host", "", "SSH target address (USER@ADDR or just ADDR); overrides all resolvers")
	return cmd
}

// bareInitSSHRunner is the function bareInitCmd uses to execute
// the remote `git config` command via ssh. Package-level var so
// tests can swap in a stub returning controlled output and errors.
// The default implementation forks a real `ssh` binary; production
// callers never override it.
var bareInitSSHRunner = func(ctx context.Context, target string, args ...string) ([]byte, error) {
	cmd := exec.CommandContext(ctx, "ssh",
		append([]string{
			"-o", "BatchMode=yes",
			"-o", "ConnectTimeout=5",
			"-o", "StrictHostKeyChecking=accept-new",
			target,
		}, args...)...)
	return cmd.CombinedOutput()
}

// resolveBareInitAddress walks the address-resolution ladder
// described in bareInitCmd's --help: explicit override → any
// available resolver → peer.Name as a last-resort hostname.
// Returns the resolved address and a short label for the source
// (used in operator-facing log lines). The "name as hostname"
// fallback exists so users who have configured their SSH client
// (via /etc/hosts, ~/.ssh/config, or local DNS) can use the peer's
// dotkeeper name as the SSH target without needing a configured
// resolver inside dotkeeper itself.
func resolveBareInitAddress(ctx context.Context, p config.PeerEntry, override string, resolvers []transport.Resolver) (addr, source string, err error) {
	if override != "" {
		return override, "override", nil
	}
	peer := transport.Peer{Name: p.Name, DeviceID: p.DeviceID, Hostname: p.Name}
	for _, r := range resolvers {
		if !r.Available() {
			continue
		}
		a, rerr := r.Resolve(ctx, peer)
		if rerr == nil {
			return a, r.Name(), nil
		}
		// ErrPeerUnknown is the expected "this resolver doesn't
		// know about this peer" signal; we move on to the next
		// resolver. Other errors (ErrResolverUnavailable, etc.)
		// also fall through; a future revision may log differently
		// to distinguish "resolver broken" from "resolver doesn't
		// know peer."
		_ = rerr
	}
	// Last-resort fallback: assume the peer name itself is an
	// SSH-reachable hostname. Works for fleets with /etc/hosts
	// entries, ~/.ssh/config Host blocks, or LAN-local DNS.
	return p.Name, "name-as-hostname", nil
}

// shellQuote returns s wrapped in single quotes with embedded
// single-quotes escaped. We use it for paths passed to remote
// shells via ssh, where the path becomes one argument to remote
// `sh -c "..."` after SSH's own argument concatenation. Without
// quoting, a path with spaces (like macOS's "/Users/me/My
// Documents") would split across multiple remote arguments.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// transportCmd surfaces the v1.0.0 multi-transport state to operators.
// Two subcommands:
//
//   - list: every transport configured in this build with its
//     current Available() state and default prior parameters.
//   - status [peer]: per-peer route table (which transports reach
//     this peer, with the discovery-time RTT and current
//     cost-model prediction).
//
// The CLI is the v1.0.0 source of truth for "what is the system
// doing right now." Future versions add `rediscover` (force a
// fresh probe), `prefer <peer> <transport>` (sticky operator
// override), and `parameters <transport> <peer>` (show learned
// cost-model coefficients with sample counts).
// transportSource is the production transport-list builder used
// by the CLI commands. Defined as a package var so tests can swap
// in a stub returning controlled transports — the default
// buildTransportList depends on a live Syncthing API key and a
// configured Tailscale binary, neither of which is appropriate
// for unit tests.
var transportSource = buildTransportList

func transportCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "transport",
		Short: "Inspect the multi-transport state (v1.0.0+)",
		Long: "List configured transports and their per-peer reachability\n" +
			"status. dotkeeper picks the optimal transport per change\n" +
			"based on a cost model that learns from observed transfer\n" +
			"durations; this command exposes the current state of that\n" +
			"system for operator inspection.",
	}
	cmd.AddCommand(transportListCmd())
	cmd.AddCommand(transportStatusCmd())
	cmd.AddCommand(transportReposCmd())
	return cmd
}

func transportListCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List every transport configured in this build",
		Long: "Shows each transport's Name and current Available() state.\n" +
			"Unavailable transports stay in the list (so operators can\n" +
			"see what could be configured) but are skipped by the\n" +
			"router until their prerequisites become satisfied.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			transports := transportSource()
			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 0, 2, ' ', 0)
			_, _ = fmt.Fprintln(w, "TRANSPORT\tAVAILABLE")
			for _, t := range transports {
				_, _ = fmt.Fprintf(w, "%s\t%s\n", t.Name(), availabilityString(t.Available()))
			}
			return w.Flush()
		},
	}
}

func transportStatusCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "status [peer]",
		Short: "Show per-peer transport reachability + cost-model state",
		Long: "Runs a one-shot discovery against the named peer (or every\n" +
			"paired peer if no argument is given) and prints the\n" +
			"resulting route table. For each (transport, peer) pair the\n" +
			"output includes:\n\n" +
			"  - REACHABLE: whether the discovery probe succeeded\n" +
			"  - PROBE-RTT: latency measured at this probe\n" +
			"  - SETUP-MS: cost model's learned setup overhead\n" +
			"  - MB-PER-SEC: cost model's learned throughput\n" +
			"  - N: effective number of observations behind the fit\n\n" +
			"Re-run after a network change (e.g. roaming to a new WiFi)\n" +
			"to refresh the probe latencies; the cost model itself\n" +
			"updates continuously from successful transfers.",
		RunE: func(cmd *cobra.Command, args []string) error {
			machine, err := config.LoadMachineConfigV2()
			if err != nil || machine == nil {
				return fmt.Errorf("load machine config: %w", err)
			}
			peers := machine.Peers
			if len(args) == 1 {
				filtered := peers[:0]
				for _, p := range peers {
					if p.Name == args[0] {
						filtered = append(filtered, p)
					}
				}
				if len(filtered) == 0 {
					return fmt.Errorf("peer %q not found in machine config", args[0])
				}
				peers = filtered
			}

			mgr := transport.NewManager(transportSource())
			ctx := cmd.Context()
			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 0, 2, ' ', 0)
			_, _ = fmt.Fprintln(w, "PEER\tTRANSPORT\tREACHABLE\tPROBE-RTT\tSETUP-MS\tMB-PER-SEC\tN")
			for _, p := range peers {
				peer := transport.Peer{Name: p.Name, DeviceID: p.DeviceID, Hostname: p.Name}
				mgr.Discover(ctx, peer)
				routes, _ := mgr.RoutesFor(p.Name)
				for _, t := range mgr.Transports() {
					entry := routes.Entries[t.Name()]
					// Empty repoID queries the cross-repo aggregate
					// slot — the right view for "how fast is this
					// transport to this peer in general," which is
					// what this CLI surface shows.
					setup, perByte, n := mgr.ModelParametersFor(t.Name(), p.Name, "")
					throughputMBps := 0.0
					if perByte > 0 {
						throughputMBps = 1.0 / perByte / 1000.0 // (1/ms-per-byte) bytes/ms => MB/s
					}
					reach := "no"
					rtt := "—"
					if entry.Reachable {
						reach = "yes"
						rtt = entry.ProbeLatency.Round(time.Millisecond).String()
					}
					_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%.1f\t%.2f\t%.1f\n",
						p.Name, t.Name(), reach, rtt, setup, throughputMBps, n)
				}
			}
			return w.Flush()
		},
	}
}

// transportReposCmd surfaces the per-(transport, peer, repo) state
// of the cost model. `dotkeeper transport status` shows the
// cross-repo aggregate — useful for "is this transport reachable
// at all" questions — but the actual routing decision is made
// per-repo, and the model can predict very different costs for
// different folders (a tiny dotfile vs a GB asset folder differ
// by orders of magnitude on the same transport).
//
// Output is intentionally dense: one row per (peer, transport,
// repo) triple, so an operator can scan for "is Mutagen winning
// my code repos but losing my asset repos?" at a glance.
//
// Probe is NOT re-run here — that's `transport status`'s job.
// This command reads the cost model state as-of-now.
func transportReposCmd() *cobra.Command {
	var peerFilter string
	var transportFilter string
	cmd := &cobra.Command{
		Use:   "repos",
		Short: "Show per-(transport, peer, repo) cost-model predictions",
		Long: "For each managed folder, prints the cost model's prediction\n" +
			"per (transport, peer) pair. Useful for understanding what\n" +
			"transport dotkeeper would route a change through and for\n" +
			"spotting tuples where the model hasn't yet accumulated\n" +
			"observations.\n\n" +
			"Columns:\n" +
			"  - PEER, TRANSPORT, REPO: the cost-model tuple\n" +
			"  - PRED@1KB: predicted cost for a 1KB change (ms)\n" +
			"  - PRED@1MB: predicted cost for a 1MB change (ms)\n" +
			"  - N: effective observations behind the fit (>=20 = converged)\n\n" +
			"Filter with --peer=NAME or --transport=NAME to narrow output.\n\n" +
			"IMPORTANT — current limitation: cost-model observations live\n" +
			"in the daemon's memory and are not (yet) persisted across\n" +
			"processes. This CLI builds a fresh manager, so the\n" +
			"predictions reflect the bootstrap priors, not the running\n" +
			"daemon's learned state. To see what the daemon would actually\n" +
			"pick, look at its INFO logs for `propagator: pushed` lines\n" +
			"which include the chosen transport and observed elapsed.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			machine, err := config.LoadMachineConfigV2()
			if err != nil || machine == nil {
				return fmt.Errorf("load machine config: %w", err)
			}
			folders := liveBenchmarkerFoldersSource()()
			if len(folders) == 0 {
				return fmt.Errorf("no managed folders")
			}

			mgr := transport.NewManager(transportSource())
			ctx := cmd.Context()
			// Discover all peers so reachability is fresh.
			for _, p := range machine.Peers {
				mgr.Discover(ctx, transport.Peer{Name: p.Name, DeviceID: p.DeviceID, Hostname: p.Name})
			}

			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 0, 2, ' ', 0)
			_, _ = fmt.Fprintln(w, "PEER\tTRANSPORT\tREPO\tPRED@1KB\tPRED@1MB\tN")
			for _, p := range machine.Peers {
				if peerFilter != "" && p.Name != peerFilter {
					continue
				}
				routes, _ := mgr.RoutesFor(p.Name)
				for _, t := range mgr.Transports() {
					if transportFilter != "" && t.Name() != transportFilter {
						continue
					}
					entry, ok := routes.Entries[t.Name()]
					if !ok || !entry.Reachable {
						continue
					}
					for _, folder := range folders {
						setup, msPerByte, n := mgr.ModelParametersFor(t.Name(), p.Name, folder.ID)
						pred1KB := setup + msPerByte*1024
						pred1MB := setup + msPerByte*(1024*1024)
						label := filepath.Base(folder.Path)
						_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%.1fms\t%.0fms\t%.1f\n",
							p.Name, t.Name(), label, pred1KB, pred1MB, n)
					}
				}
			}
			return w.Flush()
		},
	}
	cmd.Flags().StringVar(&peerFilter, "peer", "",
		"Show only this peer's predictions")
	cmd.Flags().StringVar(&transportFilter, "transport", "",
		"Show only this transport's predictions (use the full name like \"mutagen+tailscale\")")
	return cmd
}
