// Copyright (C) 2026 Julian Corbet
// SPDX-License-Identifier: AGPL-3.0-only

package config

import (
	"strings"
)

const ignoreHeader = "# Managed by dotkeeper - local Syncthing ignore rules\n" +
	"# Regenerated by dotkeeper reconcile. Do not edit by hand.\n"

// DefaultSyncIgnorePatterns are the baseline Syncthing ignore rules every
// dotkeeper-managed repo must carry. They keep local VCS state, Syncthing
// metadata, dependency caches, and build outputs out of the P2P mesh.
//
// Pattern order is load-bearing: Syncthing's matcher walks the list and
// stops at the first hit, so the highest-frequency matches go first. .git
// dominates any tree walk (every directory traversal queries it before
// descending), so it stays at the top.
//
// Pattern shape is also load-bearing: plain strings ("node_modules",
// ".cache") hit a hash table inside the matcher; globs ("*.sqlite*")
// fall through to a glob engine with string-search overhead. We
// consolidate variant families into single globs where the false-
// positive risk is acceptable — "*.sqlite*" intentionally covers
// .sqlite3 / .sqlite-wal / .sqlite-shm / .sqlite-journal and similar
// in one pattern rather than enumerating eight, because they all share
// the same "SQLite engine spilled this onto disk" semantics.
//
// Profile (2026-05-20): ignore.Matcher.Match accounted for 32.6% of the
// daemon's CPU; the variant explosion in the prior list (8 sqlite + 4
// swap + 7 pyc/egg + 2 log = 21 globs that could be 6) was the dominant
// per-pattern cost. v0.9.3 consolidation expected to drop matcher time
// by ~30-50% in steady state.
var DefaultSyncIgnorePatterns = []string{
	// VCS, Syncthing, dotkeeper control files — match on almost every walk.
	".git",
	RepoConfigFileName,
	"dotkeeper.toml",
	".stignore",
	".dkfolder",
	".stfolder",
	"*.sync-conflict-*",
	".syncthing.*.tmp",

	// OS metadata files (case-insensitive in their natural habitat).
	"(?d).DS_Store",
	"(?d)Thumbs.db",
	"(?d)desktop.ini",

	// Dependency and build-output directories (plain strings — hash-matched).
	"node_modules",
	"dist",
	"build",
	"out",
	"target",
	".wrangler",
	".deno-bin",
	".cache",
	".parcel-cache",
	".next",
	".nuxt",
	".turbo",
	".angular",
	".sass-cache",

	// AI-agent ephemera. Claude Code creates `.claude/worktrees/` for
	// transient agent sandboxes — each one is a nested `git worktree`
	// (so it contains a `.git` pointer file and may contain other
	// already-ignored content). Without this entry Syncthing tries to
	// replicate the worktree across peers, then perpetually flaps on
	// "delete directory contains ignored files" warnings every time
	// an agent finishes and the worktree is cleaned up locally.
	// Anchored path pattern — `.claude/agents`, `.claude/hooks`, and
	// `.claude/settings.json` stay synced.
	".claude/worktrees",

	// Language-server and tooling caches (plain strings).
	".pytest_cache",
	".mypy_cache",
	".ruff_cache",
	".tox",
	".gradle",
	".zig-cache",
	".rust-analyzer",
	".ccls-cache",
	".clangd",
	".ipynb_checkpoints",
	"playwright-report",
	"test-results",
	"coverage",
	"htmlcov",

	// Python virtual envs and bytecode (plain + consolidated glob).
	".venv",
	"venv",
	"__pycache__",
	"*.py[co]", // was: *.pyc, *.pyo
	"*.egg-info",
	".eggs",

	// SQLite engine spill — one glob replaces 8 enumerated variants.
	"*.sqlite*",

	// Runtime artefacts.
	"*.pid",
	"*.sock",

	// Log files (consolidated).
	"*.log*", // was: *.log, *.log.*

	// Editor swap/backup files (consolidated; covers .vim/nvim swap conventions).
	"*.sw[op]",  // was: *.swp, *.swo
	".*.sw[op]", // was: .*.swp, .*.swo  — hidden dotfile swaps
	"*~",
	"#*#",

	// Generic ephemera.
	"*.tmp",
	"*.temp",
	"*.bak",
	"*.orig",
}

// DefaultGitExcludePatterns are local dotkeeper/Syncthing control files that
// dotkeeper excludes from each managed Git working copy.
var DefaultGitExcludePatterns = []string{
	RepoConfigFileName,
	"dotkeeper.toml",
	".stignore",
	".dkfolder",
	".stfolder",
	"*.sync-conflict-*",
	".syncthing.*.tmp",
}

// MergeSyncIgnorePatterns returns the baseline ignore rules plus any per-repo
// overrides, preserving first occurrence order and dropping blank entries.
func MergeSyncIgnorePatterns(extra []string) []string {
	merged := make([]string, 0, len(DefaultSyncIgnorePatterns)+len(extra))
	seen := make(map[string]struct{}, len(DefaultSyncIgnorePatterns)+len(extra))
	add := func(pattern string) {
		pattern = strings.TrimSpace(pattern)
		if pattern == "" {
			return
		}
		if _, ok := seen[pattern]; ok {
			return
		}
		seen[pattern] = struct{}{}
		merged = append(merged, pattern)
	}
	for _, pattern := range DefaultSyncIgnorePatterns {
		add(pattern)
	}
	for _, pattern := range extra {
		add(pattern)
	}
	return merged
}

// SyncIgnoreFileContent serializes ignore rules into dotkeeper's canonical
// .stignore file content.
func SyncIgnoreFileContent(patterns []string) string {
	merged := MergeSyncIgnorePatterns(patterns)
	var b strings.Builder
	b.WriteString(ignoreHeader)
	for _, pattern := range merged {
		b.WriteString(pattern)
		b.WriteByte('\n')
	}
	return b.String()
}
