// Copyright (C) 2026 Julian Corbet
// SPDX-License-Identifier: AGPL-3.0-only

package config

import (
	"strings"
)

const ignoreHeader = "# Managed by dotkeeper - local Syncthing ignore rules\n" +
	"# Regenerated by dotkeeper reconcile. Do not edit by hand.\n"

// DefaultSyncIgnorePatterns are the baseline Syncthing ignore rules every
// dotkeeper-managed repo must carry. They keep local VCS state, Syncthing
// metadata, dependency caches, and build outputs out of the P2P mesh.
var DefaultSyncIgnorePatterns = []string{
	".git",
	RepoConfigFileName,
	"dotkeeper.toml",
	".stignore",
	".dkfolder",
	".stfolder",
	"*.sync-conflict-*",
	".syncthing.*.tmp",
	"(?d).DS_Store",
	"(?d)Thumbs.db",
	"(?d)desktop.ini",
	"node_modules",
	"dist",
	"build",
	"out",
	"target",
	".wrangler",
	".deno-bin",
	".cache",
	".parcel-cache",
	".next",
	".nuxt",
	".turbo",
	".angular",
	".sass-cache",
	".pytest_cache",
	".mypy_cache",
	".ruff_cache",
	".tox",
	".gradle",
	".zig-cache",
	".rust-analyzer",
	".ccls-cache",
	".clangd",
	".ipynb_checkpoints",
	"playwright-report",
	"test-results",
	"coverage",
	"htmlcov",
	".venv",
	"venv",
	"__pycache__",
	"*.pyc",
	"*.pyo",
	".eggs",
	"*.egg-info",
	"*.sqlite3",
	"*.sqlite3-journal",
	"*.sqlite3-wal",
	"*.sqlite3-shm",
	"*.sqlite",
	"*.sqlite-journal",
	"*.sqlite-wal",
	"*.sqlite-shm",
	"*.pid",
	"*.sock",
	"*.log",
	"*.log.*",
	"*.swp",
	"*.swo",
	".*.swp",
	".*.swo",
	"*~",
	"#*#",
	"*.tmp",
	"*.temp",
	"*.bak",
	"*.orig",
}

// DefaultGitExcludePatterns are local dotkeeper/Syncthing control files that
// dotkeeper excludes from each managed Git working copy.
var DefaultGitExcludePatterns = []string{
	RepoConfigFileName,
	"dotkeeper.toml",
	".stignore",
	".dkfolder",
	".stfolder",
	"*.sync-conflict-*",
	".syncthing.*.tmp",
}

// MergeSyncIgnorePatterns returns the baseline ignore rules plus any per-repo
// overrides, preserving first occurrence order and dropping blank entries.
func MergeSyncIgnorePatterns(extra []string) []string {
	merged := make([]string, 0, len(DefaultSyncIgnorePatterns)+len(extra))
	seen := make(map[string]struct{}, len(DefaultSyncIgnorePatterns)+len(extra))
	add := func(pattern string) {
		pattern = strings.TrimSpace(pattern)
		if pattern == "" {
			return
		}
		if _, ok := seen[pattern]; ok {
			return
		}
		seen[pattern] = struct{}{}
		merged = append(merged, pattern)
	}
	for _, pattern := range DefaultSyncIgnorePatterns {
		add(pattern)
	}
	for _, pattern := range extra {
		add(pattern)
	}
	return merged
}

// SyncIgnoreFileContent serializes ignore rules into dotkeeper's canonical
// .stignore file content.
func SyncIgnoreFileContent(patterns []string) string {
	merged := MergeSyncIgnorePatterns(patterns)
	var b strings.Builder
	b.WriteString(ignoreHeader)
	for _, pattern := range merged {
		b.WriteString(pattern)
		b.WriteByte('\n')
	}
	return b.String()
}
